# Generated by Django 4.0.5 on 2022-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='default'),
        ),
    ]
